version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/u19-python-pipeline
    ports:
      - "8800:8888"
